### ISSUE TITLE
empty range for randrange() (%d,%d, %d) when there is no source file

### ISSUE THREAD

**Issue by josuebasurto** [bitsofinfo/log-generator#3]
```
➜  Devops python servermonitor.py --logFile def.txt
######################################
### log-generator running with.....
######################################
sourceDataFile: defaultDataFile.txt
logPattern: %(asctime)s,%(msecs)d %(process)d %(filename)s %(lineno)d %(name)s %(levelname)s %(message)s
datePattern: %Y-%m-%d %H:%M:%S
sourceData lines: -1
minSleep: 0.1
maxSleep: 1
minLines: 1
maxLines: -1
######################################
Traceback (most recent call last):
  File "servermonitor.py", line 142, in <module>
    main(sys.argv[1:])
  File "servermonitor.py", line 115, in main
    lineToStart = random.randint(0,totalLines)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/random.py", line 244, in randint
    return self.randrange(a, b+1)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/random.py", line 220, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
```

**Comment by bitsofinfo** [comment]
Thanks! please feel free to submit a PR fix and I'll get it in!

**Comment by josuebasurto** [comment]
Sure! Thanks for response... Will do!

**Comment by bitsofinfo** [comment]
pr merged, thanks!
